// Bootstrap the topup app from a one-tap link generated by Alby Hub.
//
// The link looks like:
//   https://card.albylabs.com/#label=RedotPay&address=0x...&chainId=42161&currency=USDC&nwc=<urlencoded-pairing-uri>
//
// Why a URL hash (anchor):
//  - Hash fragments are CLIENT-SIDE ONLY — browsers never include them in
//    HTTP requests, so the NWC secret never reaches GitHub Pages / any
//    server log / Referer header.
//  - Immediately after we read the hash we strip it from the URL and the
//    browser history via history.replaceState, so the secret doesn't sit
//    in the address bar, get bookmarked, or get captured by any client-side
//    analytics that reads document.URL.
//  - Never log the nwc value to the console.

import { isAddress } from "viem";
import {
  SUPPORTED_CHAINS,
  SUPPORTED_CURRENCIES,
  type SupportedCurrency,
} from "./lendaswap";
import type { CardConfig } from "./config";

export type HashBootstrap = {
  config: CardConfig | null;
  nwcUri: string | null;
};

function clearHashFromUrl() {
  if (typeof history === "undefined") return;
  // Drop the fragment AND any nwc=... so it doesn't sit in the URL bar.
  // Use replaceState so it also disappears from the back-button history.
  history.replaceState(
    null,
    "",
    window.location.pathname + window.location.search,
  );
}

export function readHashBootstrap(): HashBootstrap {
  const empty: HashBootstrap = { config: null, nwcUri: null };

  if (typeof window === "undefined") return empty;
  const raw = window.location.hash;
  if (!raw || raw === "#") return empty;

  // URLSearchParams handles "#foo=bar&baz=qux" once we strip the leading #.
  const params = new URLSearchParams(raw.replace(/^#/, ""));
  if (![...params.keys()].length) return empty;

  // -- Parse config bits (all optional individually, but only commit if the
  //    required ones are present and valid) ------------------------------
  const label = params.get("label") ?? undefined;
  const address = params.get("address");
  const chainIdRaw = params.get("chainId");
  const currencyRaw = params.get("currency");

  let config: CardConfig | null = null;
  if (address && chainIdRaw && currencyRaw) {
    const chainId = Number(chainIdRaw);
    const currency = currencyRaw as SupportedCurrency;
    if (
      isAddress(address) &&
      SUPPORTED_CHAINS.some((c) => c.chainId === chainId) &&
      SUPPORTED_CURRENCIES.includes(currency)
    ) {
      config = {
        label: label?.trim() || undefined,
        destinationAddress: address as `0x${string}`,
        chainId,
        currency,
      };
    }
  }

  // -- NWC URI ----------------------------------------------------------
  // Only accept obviously-shaped values. Don't log this on failure.
  const nwcRaw = params.get("nwc");
  const nwcUri =
    nwcRaw && nwcRaw.startsWith("nostr+walletconnect://") ? nwcRaw : null;

  // Strip the hash regardless of whether anything was valid, so a stale or
  // tampered link doesn't linger in the address bar.
  clearHashFromUrl();

  return { config, nwcUri };
}
